// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ5Mwvlz-xgeDdwmNnwNwCyLx9M5xrGdA',
    appId: '1:117312833377:web:a489c5de3f11a9f915a720',
    messagingSenderId: '117312833377',
    projectId: 'mobile-6bb23',
    authDomain: 'mobile-6bb23.firebaseapp.com',
    storageBucket: 'mobile-6bb23.firebasestorage.app',
    measurementId: 'G-87S8PPVR6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkbHf8S5xpPidjHqhtwnhODUbqCY1SbUg',
    appId: '1:117312833377:android:49db739adf3db80a15a720',
    messagingSenderId: '117312833377',
    projectId: 'mobile-6bb23',
    storageBucket: 'mobile-6bb23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1oQkImNKkFC4Kqz6-Hlmk6-1SOyl-0A0',
    appId: '1:117312833377:ios:4d5be2c7f7b939d115a720',
    messagingSenderId: '117312833377',
    projectId: 'mobile-6bb23',
    storageBucket: 'mobile-6bb23.firebasestorage.app',
    iosBundleId: 'com.example.gemStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1oQkImNKkFC4Kqz6-Hlmk6-1SOyl-0A0',
    appId: '1:117312833377:ios:4d5be2c7f7b939d115a720',
    messagingSenderId: '117312833377',
    projectId: 'mobile-6bb23',
    storageBucket: 'mobile-6bb23.firebasestorage.app',
    iosBundleId: 'com.example.gemStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ5Mwvlz-xgeDdwmNnwNwCyLx9M5xrGdA',
    appId: '1:117312833377:web:e28b4223ae53506615a720',
    messagingSenderId: '117312833377',
    projectId: 'mobile-6bb23',
    authDomain: 'mobile-6bb23.firebaseapp.com',
    storageBucket: 'mobile-6bb23.firebasestorage.app',
    measurementId: 'G-VWZ33SR2WV',
  );
}
